name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    env:
      INSTALL_CMD: "npm ci"
      LINT_CMD: "npm run lint || echo 'no-lint'"
      TEST_CMD: "npm test -- --ci || echo 'no-tests'"
      BUILD_CMD: "npm run build"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: $INSTALL_CMD

      - name: Lint
        run: $LINT_CMD

      - name: Test
        run: $TEST_CMD

      - name: Build
        run: $BUILD_CMD
